# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='text',
            field=models.TextField(default=b'project_default'),
        ),
    ]
